cuisine/urls.py
from django.conf.urls import patterns, include, url
from django.contrib import admin
from django.conf import settings

urlpatterns = patterns('',
    url(r'^admin/', include(admin.site.urls)),
    url(r'^account/login/$', 'django.contrib.auth.views.login', name="login"),
    url(r'^account/logout/$', 'django.contrib.auth.views.logout',{'next_page': '/'}, name="logout"),
    url(r'^', include('recette.urls', namespace='recette')),
)


if settings.DEBUG:
    # static files (images, css, javascript, etc.)
    urlpatterns += patterns('',
        (r'^medias/(?P<path>.*)$', 'django.views.static.serve', {
        'document_root': settings.MEDIA_ROOT}))

recette/urls.py
from django.conf.urls import patterns, include, url
from .views import index, recette, register, nouvelleRecette, search, mes_recettes, supprimerRecette, modifyRecette


urlpatterns = patterns('',
    url(r'^$', index, name='index'),
    url(r'^recette/(?P<id>\d+)/', recette, name="recette"),
    url(r'^ajouter$', nouvelleRecette, name="ajout"),
    url(r'^account/register/$', register, name='register'),
    url(r'^search_result/$', search, name='search'),
    url(r'^mes_recettes/$', mes_recettes, name='mesrecettes'),
    url(r'^supprimer_recette/(?P<id>\d+)/', supprimerRecette, name='supprimerrecette'),
    url(r'^modify_recette/(?P<id>\d+)/', modifyRecette, name='modify_recette'),
)

recette/models.py
from django.db import models
from django.contrib.auth.models import User
from django.db.models.aggregates import Avg
from datetime import datetime

class Recette(models.Model):
    user = models.ForeignKey(User,default=1,editable=False)
    type = models.ForeignKey('Type', null=True)
    titre = models.CharField(max_length=100)
    cout = models.FloatField(null=True)
    difficulte = models.ForeignKey('Difficulte',default=1)
    temps_preparation = models.IntegerField(null=True)
    temps_cuisson = models.IntegerField(null=True)
    temps_repos = models.IntegerField(null=True)


    def calculateAvg(self):
        return Note.objects.filter(recette = self).aggregate(Avg('note'))

    moyenne_note = property(calculateAvg)

    def __str__(self):
        return self.titre




class Photo(models.Model):
    recette = models.ForeignKey('Recette',null=True,editable=False)
    image = models.ImageField(upload_to="photos_recettes", max_length=100)


class Ingredient(models.Model):
    recette = models.ForeignKey('Recette', null=True,editable=False)
    nom = models.CharField(max_length=100)
    quantite = models.CharField(max_length=100)


class Etape(models.Model):
    recette = models.ForeignKey('Recette', null=True, editable=False)
    detail = models.TextField()


class Type(models.Model):
    title = models.CharField(max_length=256)
    label = models.CharField(max_length=100,default='Label')
    detail = models.TextField()

    def __str__(self):
        return self.title


class Difficulte(models.Model):
    text = models.CharField(max_length=100)

    def __str__(self):
        return self.text

CHOICES = [(i,i) for i in range(11)]

class Note(models.Model):
    recette = models.ForeignKey('Recette', blank=True, null=True)
    user = models.ForeignKey(User, blank=True, null=True)
    note = models.IntegerField(choices=CHOICES)

    def __str__(self):
        return '%s' % (self.note)


class Commentaire(models.Model):
    recette = models.ForeignKey('Recette', blank=True, null=True)
    user = models.ForeignKey(User, blank=True, null=True, default=1)
    message = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True,default=datetime.now, blank=True, null=True)

recette/forms.py
from django import forms
from .models import Recette, Etape, Ingredient , Note, Commentaire, Photo
from django.forms.models import inlineformset_factory
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class RecetteForm(forms.ModelForm):
    required_css_class = 'required'
    class Meta:
        model = Recette

class EtapeCustomForm(forms.ModelForm):
    required_css_class = 'required'
    detail = forms.CharField(required = True, widget=forms.Textarea(attrs={'cols': 40, 'rows': 2}))
    class Meta:
        model = Etape


IngredientFormset = inlineformset_factory(Recette, Ingredient,can_delete=False)
EtapeFormset = inlineformset_factory(Recette, Etape,form=EtapeCustomForm,can_delete=False)
ImageFormset = inlineformset_factory(Recette, Photo,can_delete=False)


class NoteForm(forms.ModelForm):
    class Meta:
        model = Note
        fields = ['note']


class CommentaireForm(forms.ModelForm):
    message = forms.CharField(widget=forms.Textarea(attrs={'cols': 100, 'rows': 5}))
    class Meta:
        model = Commentaire
        fields = ['message']


class TestForm(forms.Form):
    nom = forms.CharField(max_length=100)
    prenom = forms.CharField(max_length=100,required='true')


class RegistrationForm(UserCreationForm):
    required_css_class = 'required'
    email = forms.EmailField(required = True)
    first_name = forms.CharField(required = True, label="Prénom")
    last_name = forms.CharField(required = True, label="Nom")

    class Meta:
        model = User
        fields = ('username', 'email', 'password1', 'password2')

    def save(self,commit = True):
        user = super(RegistrationForm, self).save(commit = False)
        user.email = self.cleaned_data['email']
        user.first_name = self.cleaned_data['first_name']
        user.last_name = self.cleaned_data['last_name']

        if commit:
            user.save()

        return user

recette/views.py
from django.shortcuts import render, redirect
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from .forms import RecetteForm,EtapeFormset,RegistrationForm,IngredientFormset,ImageFormset, CommentaireForm, NoteForm, EtapeCustomForm
from .models import Ingredient,  Etape,  Photo,  Recette, Note, Commentaire, Type
from django import template
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger
import pprint
from django.forms.models import inlineformset_factory
from django.forms.formsets import formset_factory
from django.db.models import Avg
from recette.views import Recette
from django.http import HttpResponseRedirect, HttpResponse
from django.core.urlresolvers import reverse
from django.contrib.auth.forms import AuthenticationForm
from django.shortcuts import get_list_or_404, get_object_or_404
from django.forms.models import modelformset_factory

TYPE_CHOICES = ['1','2','3','4'];

def index(request):

    recettes = Recette.objects.all().order_by('-id');
    typeObjet=None
    if request.method == 'GET':
        if request.GET.get('type'):
            if request.GET['type'] in TYPE_CHOICES:
                type = request.GET['type']
                typeObjet = Type.objects.get(id=type)
                recettes = Recette.objects.filter(type=type);
    paginator = Paginator(recettes, 10)
    page = request.GET.get('page')
    try:
        recettes = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        recettes = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        recettes = paginator.page(paginator.num_pages)
    contexte = {
        'typeObjet': typeObjet,
        'recettes': recettes,
    }
    return render(request, 'recette/index.html', contexte)


def register(request):
    if (request.method == 'POST'):
        user_form = RegistrationForm(request.POST)
        if user_form.is_valid():
            user = User.objects.create_user(request.POST['username'],request.POST['email'],request.POST['password1'])
            user.first_name = request.POST['first_name']
            user.last_name = request.POST['last_name']
            user.save()
            contexte = {
                'form': AuthenticationForm,
                'success_message':'success'
            }
            return render(request, 'registration/login.html', contexte)
    else:
        user_form = RegistrationForm()
    contexte = {
        'formulaire': user_form,
    }
    return render(request, 'registration/register.html', contexte)


def recette(request, id):

    if (request.method == 'POST'):
        note_form = NoteForm(request.POST)
        commentaire_form = CommentaireForm(request.POST)

        if note_form.is_valid():
            note = note_form.save()
            note.recette = Recette.objects.get(id=id)
            note.user = request.user
            note.save()

        if commentaire_form.is_valid():
            commentaire = commentaire_form.save()
            commentaire.recette = Recette.objects.get(id=id)
            commentaire.user = request.user
            commentaire.save()

    recette = Recette.objects.get(id=id)
    etapes = Etape.objects.filter(recette=id)
    ingredients = Ingredient.objects.filter(recette=id)
    photos = Photo.objects.filter(recette=id)
    note = Note.objects.filter(recette=id).aggregate(Avg('note'))
    noted = 0
    if(request.user.is_authenticated()):
        noted = Note.objects.filter(recette=id,user=request.user).count()
    form_note = ''
    if noted == 0:
        form_note = NoteForm();
    commentaires = Commentaire.objects.filter(recette=id)
    form_com = CommentaireForm();
    contexte = {
        'recette'    : recette,
        'etapes'     : etapes,
        'ingredients': ingredients,
        'photos'     : photos,
        'note'     : note,
        'commentaires'     : commentaires,
        'form_note': form_note,
        'form_com': form_com,
    }
    return render(request, 'recette/affiche-recette.html', contexte)

def nouvelleRecette(request):

    form = RecetteForm()
    IngredientForm = IngredientFormset()
    EtapeForm = EtapeFormset()
    ImageForm = ImageFormset()

    if request.method == 'POST':
        form = RecetteForm(request.POST)
        if form.is_valid():
            recette = form.save()
            recette.user = request.user
            recette.save()
            IngredientForm = IngredientFormset(request.POST,instance=recette)
            if IngredientForm.is_valid():
                IngredientForm.save()
                EtapeForm = EtapeFormset(request.POST,instance=recette)
                if EtapeForm.is_valid():
                    EtapeForm.save()
                    ImageForm = ImageFormset(request.POST,request.FILES,instance=recette)
                    if ImageForm.is_valid():
                        ImageForm.save()
                        return render(request, "recette/nouvelle-recette.html", {
                            'form': form,
                            'IngredientForm': IngredientForm,
                            'EtapeForm': EtapeForm,
                            'ImageForm': ImageForm,
                            'success_message':'success'
                        })

    return render(request, "recette/nouvelle-recette.html", {
        'form': form,
        'IngredientForm': IngredientForm,
        'EtapeForm': EtapeForm,
        'ImageForm':ImageForm,
    })


def modifyRecette(request, id):
    recette = get_object_or_404(Recette, id=id)

    ingredientFormSetCustom = modelformset_factory(Ingredient)
    etapeFormSetCustom = modelformset_factory(Etape, form=EtapeCustomForm)
    photoFormSetCustom = modelformset_factory(Photo)

    ingredients = Ingredient.objects.filter(recette=recette)
    etapes = Etape.objects.filter(recette=recette)
    photos = Photo.objects.filter(recette=recette)

    IngredientForm = ingredientFormSetCustom(queryset=ingredients)
    EtapeForm = etapeFormSetCustom(queryset=etapes)
    ImageForm = photoFormSetCustom(queryset=photos)
    formRecette = RecetteForm(instance=recette)

    if request.method == 'POST':
        form = RecetteForm(request.POST)
        if form.is_valid():
            recette.type_id = form.cleaned_data['type']
            recette.titre = form.cleaned_data['titre']
            recette.cout = form.cleaned_data['cout']
            recette.difficulte = form.cleaned_data['difficulte']
            recette.temps_preparation = form.cleaned_data['temps_preparation']
            recette.temps_cuisson = form.cleaned_data['temps_cuisson']
            recette.temps_repos = form.cleaned_data['temps_repos']
            recette.user = request.user
            recette.save()

            results = Recette.objects.filter(user_id=request.user.id)
            contexte = {
                'results': results,
                'success_message':'success'
            }
            return render(request, 'recette/mes_recettes.html', contexte)

    return render(request, "recette/modify-recette.html", {
        'recette': recette,
        'form': formRecette,
        'IngredientForm': IngredientForm,
        'EtapeForm': EtapeForm,
        'ImageForm':ImageForm,
    })


def supprimerRecette(request, id):
    Recette.objects.get(id=id).delete()
    results = Recette.objects.filter(user_id=request.user.id)
    contexte = {
        'results': results
    }
    return render(request, 'recette/mes_recettes.html', contexte)

def search(request):

    query = request.GET.get('search_query')
    orderby = ''
    orderway = ''
    if request.GET.get('orderby') and request.GET.get('orderway'):
        orderby = request.GET.get('orderby')
        orderway = request.GET.get('orderway')
        if orderway == 'desc':
            results = Recette.objects.filter(titre__contains=query).order_by('-' + orderby).select_related()
        elif orderway == 'asc':
            results = Recette.objects.filter(titre__contains=query).order_by(orderby).select_related()
    else :
        results = Recette.objects.filter(titre__contains=query).select_related()

    paginator = Paginator(results, 10)
    page = request.GET.get('page')
    try:
        results = paginator.page(page)
    except PageNotAnInteger:
        # If page is not an integer, deliver first page.
        results = paginator.page(1)
    except EmptyPage:
        # If page is out of range (e.g. 9999), deliver last page of results.
        results = paginator.page(paginator.num_pages)
    contexte = {
        'page': page,
        'orderby': orderby,
        'orderway': orderway,
        'query': query,
        'results' : results
    }
    return render(request, 'search/search_result.html', contexte)

def mes_recettes(request):
    results = None;
    if request.user.is_authenticated():
        results = Recette.objects.filter(user_id=request.user.id)
    contexte = {
        'results': results
    }
    return render(request, 'recette/mes_recettes.html', contexte)

recette/templates/recette/_base.html
{% load static %}
{% load helper %}
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        <title>{% block titre %}{% endblock %}</title>
        <link rel="stylesheet" type="text/css" href="../../static/css/styles.css">
        <link rel="stylesheet" type="text/css" href="../../static/css/bootstrap.css">
        <link rel="stylesheet" type="text/css" href="../../static/css/jquery.fancybox.css">
        <script src="../../static/js/jquery-1.11.3.min.js"></script>
        <script src="../../static/js/jquery.fancybox.js"></script>
        <link href='http://fonts.googleapis.com/css?family=Open+Sans:400,700,600' rel='stylesheet' type='text/css'>
    </head>
    <body>
        <div id="header" class="row">
            <div class="pre-header">
                <div>
                    {% show_nb_recette %}
                    <div class="user-infos">
                        {% if user.is_authenticated %}
                            {{ user.first_name }}
                            {{ user.last_name }}
                        {% else %}
                            Connectez-vous !
                        {% endif %}
                    </div>
                </div>
            </div>
            <div class="account-header">
                <div>
                    <a id="logo" href="{% url 'recette:index' %}"><img src="../../static/images/logo.png" alt="" title=""></a>
                    {% include "search/search_form.html" %}
                    <div class="account-action">
                        {% if user.is_authenticated %}
                            <a href="{% url 'recette:mesrecettes' %}">Mes recettes</a>
                            <a href="{% url 'logout' %}">Déconnexion</a>
                        {% else %}
                            <a href="{% url 'recette:register' %}" style="">S'enregistrer</a>
                            <a href="{% url 'login' %}">Connexion</a>
                        {% endif %}
                    </div>
                </div>
            </div>
            <div id="menu">
                <ul>
                    {% show_menu %}
                    <li class="add-recette">
                        {% if user.is_authenticated %}
                            <a href="{% url 'recette:ajout' %}" title="">Ajouter une recette</a>
                        {% endif %}
                    </li>
                </ul>
            </div>
        </div>
        <div id="main_container">
            <div id="main">
                <div id="page">
                    {% block contenu %}{% endblock %}
                </div>
            </div>
        </div>
        <div id="footer">
            <div>
                <div class="message">
                    <span>Site universitaire</span>
                </div>
                <div class="footer_links">
                    {% if user.is_authenticated %}
                        <a href="{% url 'logout' %}">Déconnexion</a>
                    {% else %}
                        <a href="{% url 'recette:register' %}" style="">S'enregistrer</a>
                        <a href="{% url 'login' %}">Connexion</a>
                    {% endif %}
                </div>
            </div>
        </div>
    </body>
</html>

recette/templates/recette/affiche-recette.html
{% extends 'recette/_base.html' %}
{% block titre %}Recette -{{ recette.titre }} {% endblock %}
{% block contenu %}
<div class="recette-contain">
    <div class="main-recette">
        <h1> {{ recette.titre }}</h1>
        <span class="recette-detail">
            <span class="first">Type : {{ recette.type }}</span> -
            <span>Cout : {{ recette.cout }} €</span> -
            <span>Difficulté : {{ recette.difficulte }}</span>
        </span>
    <div class="note">
        <div class="note-moyenne">Note moyenne : {{ note.note__avg|floatformat:"2" }} / 10</div>
        <div class="form_note">
            {% if user.is_authenticated %}
                {% if form_note %}
                     <form action="{% url 'recette:recette' recette.id %}" method="post">
                    {{ form_note }}
                    {% csrf_token %}
                     <input type="submit" class="btn btn-primary" value="Noter !">
                    </form>
                {% else %}
                    <span>Vous avez déjà voté !</span>
                {% endif %}
            {% else %}
                <a href="{% url 'login' %}">Connectez-vous pour donner une note à cette recette de malade !</a>
            {% endif %}
        </div>
    </div>
    </div>
    <div class="photos col-sm-5">
        <ul>
            {% for photo in photos %}
                <li><a class="fancybox" rel="gallery1" href="{{ photo.image.url }}"><img class="{% if forloop.counter == 1%}col-sm-12 first{% else %}col-sm-6{% endif %}" src="{{ photo.image.url }}"/></a></li>
            {% endfor %}
        </ul>
    </div>
    <div class="recette-right col-sm-7">
        <div class="temps">
            <ul>
                <li><span>Temps de cuisson :</span> {{ recette.temps_cuisson }} minutes</li>
                <li><span>Temps de preparation :</span> {{ recette.temps_preparation }} minutes</li>
                <li><span>Temps de repos :</span> {{ recette.temps_repos }} minutes</li>
            </ul>
        </div>
        <div class="etapes">
            <h4> Etapes :</h4>
            <ul>
                {% for etape in etapes %}
                    <li> {{ etape.detail }}  </li>
                {% endfor %}
            </ul>
        </div>
        <div class="ingredients">
            <h4> Ingrédients :</h4>
            <ul>
                {% for ingredient in ingredients %}
                    <li> {{ ingredient.nom }} : {{ ingredient.quantite }}  </li>
                {% endfor %}
            </ul>
        </div>
    </div>

    <div class="form_com col-sm-12">
        <h3> Commentaires :</h3>
        <div class="commentaire">
            <ul>
                {% for com in commentaires %}
                    <li>
                        <span>{{ com.user }} le {{ com.created_at }}</span>
                        <div>{{ com.message }}</div>
                    </li>
                {% endfor %}
            </ul>
        </div>
        {% if user.is_authenticated %}
            {% if form_com %}
                <h4>Ajouter un commentaire</h4>
                <form action="{% url 'recette:recette' recette.id %}" method="post">
                {{ form_com }}
                {% csrf_token %}
                 <input type="submit" class="btn btn-primary" value="Commenter">
                </form>
            {% else %}
                Vous avez déjà voté !
            {% endif %}
        {% else %}
            <a href="{% url 'login' %}">Connectez-vous pour laisser un commentaire à cette recette de malade !</a>
        {% endif %}
    </div>
</div>
<script type="text/javascript">
    $(document).ready(function() {
        $(".fancybox").fancybox({
            openEffect	: 'none',
            closeEffect	: 'none'
        });
    });
</script>
{% endblock %}

recette/templates/recette/index.html
{% extends 'recette/_base.html' %}
{% block titre %}Liste des sondages{% endblock %}
{% block contenu %}
    {% if typeObjet %}
        <h1>{{ typeObjet.label }}</h1>
        <div>{{ typeObjet.detail }}</div>
    {% else %}
        <h1>Voici toutes nos recettes !</h1>
    {% endif %}
    {% if recettes %}
        <table class="table table-hover search-result">
            <thead>
                <tr>
                    <th>Photo</th>
                    <th>Titre</th>
                    <th>Difficulté</th>
                    <th>Note moyenne</th>
                    <th>Temps de préparation</th>
                </tr>
            </thead>
            <tbody>
            {% for result in recettes %}
                <tr>
                    <td>
                        <a href="{% url 'recette:recette' result.id %}">
                            <img src="{% if result.photo_set.all %}{% for photo in result.photo_set.all %}{% if forloop.counter == 1%}{{ photo.image.url }}{% endif %}{% endfor %}{% else %}{{ STATIC_URL }}images/no-image.png{% endif %}" alt="" />
                        </a>
                    </td>
                    <td><a href="{% url 'recette:recette' result.id %}">{{ result.titre }}</a></td>
                    <td>{{ result.difficulte }}</td>
                    <td>{% if result.moyenne_note.note__avg %}{{ result.moyenne_note.note__avg|floatformat:"2" }}{% else %}Pas de notes{% endif %}</td>
                    <td>{{ result.temps_preparation }} minutes</td>
                </tr>
            {% endfor %}
            </tbody>
        </table>
        <div class="pagination">
            <span class="step-links">
                {% if recettes.has_previous %}
                    <a href="?type={{ typeObjet.id }}&page={{ recettes.previous_page_number }}">Résultats précédent</a>
                {% endif %}

                <span class="current">
                    Page {{ recettes.number }} de {{ recettes.paginator.num_pages }}
                </span>

                {% if recettes.has_next %}
                    <a href="?type={{ typeObjet.id }}&page={{ recettes.next_page_number }}">Résultats suivant</a>
                {% endif %}
            </span>
        </div>
    {% else %}
        <h2>Aucune recette</h2>
    {% endif %}
{% endblock %}

recette/templates/recette/menu.html
<li><a href="{% url 'recette:index' %}">Acceuil</a></li>
{% for type in types %}
    <li><a href="{% url 'recette:index' %}?type={{ type.id }}">{{ type.label }}</a></li>
{% endfor %}

recette/templates/recette/mes_recettes.html
{% extends 'recette/_base.html' %}
{% block contenu %}
    {% if results %}
    <h1>J'ai actuellement {{ results.count }} recettes.</h1>

    {% if success_message %}
        <h5 class="success_message">Votre recette a bien été modifié !</h5>
    {% endif %}

    <table class="table table-hover search-result my-recettes">
        <thead>
            <tr>
                <th>Photo</th>
                <th>Titre</th>
                <th>Difficulté</th>
                <th>Note moyenne</th>
                <th>Temps de préparation</th>
                <th>Modifier</th>
                <th>Supprimer</th>
            </tr>
        </thead>
        <tbody>
            {% for result in results %}
                <tr>
                    <td>
                        <a href="{% url 'recette:recette' result.id %}">
                            <img src="{% if result.photo_set.all %}{% for photo in result.photo_set.all %}{% if forloop.counter == 1%}{{ photo.image.url }}{% endif %}{% endfor %}{% else %}{{ STATIC_URL }}images/no-image.png{% endif %}" alt="" /></td>
                        </a>
                    <td><a href="{% url 'recette:recette' result.id %}">{{ result.titre }}</a></td>
                    <td>{{ result.difficulte }}</td>
                    <td>{% if result.moyenne_note.note__avg %}{{ result.moyenne_note.note__avg|floatformat:"2" }}{% else %}Pas de notes{% endif %}</td>
                    <td>{{ result.temps_preparation }} minutes</td>
                    <td class="link modify"><a href="{% url 'recette:modify_recette' result.id %}">Modifier</a></td>
                    <td class="link supr"><a href="{% url 'recette:supprimerrecette' result.id %}">Supprimer</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% else %}
        <h1>Je n'ai pas de recettes.</h1>
    {% endif %}
{% endblock %}

recette/templates/recette/modify-recette.html
{% extends 'recette/_base.html' %}
{% block titre %}Recette  {% endblock %}
{% block contenu %}
    <h1>Ajouter une recette !</h1>

    {% if success_message %}
        <h5 class="success_message">Votre recette a bien été créée ! <a href="{% url 'recette:mesrecettes' %}">Consulter mes recettes</a></h5>
    {% endif %}

    <div style="">
    {% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
    {% endif %}
    <form action="{% url 'recette:modify_recette' recette.id %}" class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <h3>Recette :</h3>
        {{ form.as_p }}
        <h3>Ingrédients :</h3>
        {{ IngredientForm.as_p }}
        <h3>Etapes :</h3>
        {{ EtapeForm.as_p }}
        <h3>Photos :</h3>
        {{ ImageForm.as_p }}
        <input class="btn btn-primary" type="submit" value="Modifier la recette !" />
    </form>
</div>
{% endblock %}

recette/templates/recette/nb_recette_total.html
{{ nb_total }} recettes en lignes !

recette/templates/recette/nouvelle-recette.html
{% extends 'recette/_base.html' %}
{% block titre %}Recette  {% endblock %}
{% block contenu %}
    <h1>Ajouter une recette !</h1>

    {% if success_message %}
        <h5 class="success_message">Votre recette a bien été créée ! <a href="{% url 'recette:mesrecettes' %}">Consulter mes recettes</a></h5>
    {% endif %}

    <div style="">
    {% if form.subject.errors %}
    <ol>
    {% for error in form.subject.errors %}
        <li><strong>{{ error|escape }}</strong></li>
    {% endfor %}
    </ol>
    {% endif %}
    <form action="{% url 'recette:ajout' %}" class="form" method="post" enctype="multipart/form-data">
    {% csrf_token %}
        <h3>Recette :</h3>
        {{ form.as_p }}
        <h3>Ingrédients :</h3>
        {{ IngredientForm.as_p }}
        <h3>Etapes :</h3>
        {{ EtapeForm.as_p }}
        <h3>Photos :</h3>
        {{ ImageForm.as_p }}
        <input class="btn btn-primary" type="submit" value="Ajouter la recette !" />
    </form>
</div>
{% endblock %}